### ISSUE TITLE
Traversing children

### ISSUE THREAD

**Issue by ebkalderon** [ebkalderon/tq#2]
It should be possible to traverse children using identifiers and string indexing. The definition of an identifier will need to be adjusted to include `-` to accommodate [TOML's definition of a key identifier](https://github.com/toml-lang/toml#keys).

### Input TOML

```toml
[first]
foo = "bar"

[first.second]
long-name = [1, 2]
```

### Filter

_Identifier style:_

```
.hello.there.long-name
```

_String index style:_

```
.["hello"].["there"].["long-name"]
```

### Output

```
[
    1,
    2
]
```
