### ISSUE TITLE
Piping filters

### ISSUE THREAD

**Issue by ebkalderon** [ebkalderon/tq#6]
It should be possible to pipe the output of one filter into the input of another filter, like so:

### Input TOML

```toml
[first]
foo = "bar"

[first.second]
long-name = [1, 2]
```

### Filter

```
.first.second.long[] | . + 2
```

### Output

```
3
4
```
